name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - 
        name: test
        run: pwd && cd devices/hmi/app && ls && pwd
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
        working-directory: devices/hmi/app/edge-app
      - run: npm run build
        working-directory: devices/hmi/app/edge-app
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:devices/hmi/app/edge-app/"
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carbonmeter-webapp:latest
