name: Export draw.io to PNG
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo apt install x11-xserver-utils
        
      - name: Install deps
        run: sudo apt install xvfb
    
     # - name: Set environment variable
     #   run: echo "{DISPLAY}={:0}" >> $GITHUB_ENV
        
     # - name: set xhost  
     #   run: xhost +
        
     # - name: another export
     #   run: echo "{DISPLAY}={$IP:0}" >> $GITHUB_ENV
        
      - uses: actions/checkout@v3
      
      - name: Install deps
        run: sudo apt install libappindicator3-1
        
      - name: Download draw.io desktop app
        run: wget
          https://github.com/jgraph/drawio-desktop/releases/download/v13.0.3/draw.io-amd64-13.0.3.deb
          
      - name: install draw.io desktop app
        run: sudo dpkg -i draw.io-amd64-13.0.3.deb
        
      - name: Export png from xml
        run: xvfb-run drawio -x -f png -o ./reporting/docs/cems-processes.png ./reporting/docs/cems-processes.drawio --no-sandbox
        
      #- uses: actions-js/push@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit report
        run: |
          git config --global user.name 'KSilkThread'
          git config --global user.email '12004185+KSilkThread@users.noreply.github.com'
          git add reporting/docs/cems-processes.png
          git commit -am "Export process model"
          git push
