name: Minifab Image Docker

on:
  push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout and change of submodul on runner
        uses: actions/checkout@v3

      -
        name: Checkout submodules
        run: git submodule update --init --recursive
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      -
        run: python3 overwriteImagesInSubmodule.py
        working-directory: deployment/setup/ImageDownload
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: deployment/minifabric
          file: deployment/minifabric/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/minifabric:latest